package com.edu.rabbitmq.service;

import com.edu.rabbitmq.config.MessagingConfig;
import com.edu.rabbitmq.dto.OrderDTO;
import com.edu.rabbitmq.dto.OrderStatus;
import com.edu.rabbitmq.entity.Order;
import com.edu.rabbitmq.mapper.OrderMapper;
import com.edu.rabbitmq.repository.OrderRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class OrderService {

    private final RabbitTemplate template;
    private final OrderRepository orderRepository;
    private final OrderMapper orderMapper;

    @Transactional
    public OrderDTO save(OrderDTO orderDto, String restaurantName) {

        // Map DTO to entity (ID will be auto-generated by Hibernate)
        Order order = orderMapper.mapDtoToOrder(orderDto);
        
        // Save order to DB first to get the generated ID
        Order savedOrder = orderRepository.save(order);
        
        // Map saved entity back to DTO to return complete order with generated ID
        OrderDTO savedDto = orderMapper.mapOrderToDTO(savedOrder);
        
        OrderStatus orderStatus = new OrderStatus(savedDto, "IN PROGRESS", "Order sent to UberEats for restaurant: " + restaurantName);
        //Publish to RabbitMQ
        template.convertAndSend(MessagingConfig.EDU_EXCHANGE, MessagingConfig.EDU_ROUTING_KEY, orderStatus);
        
        return savedDto;
    }

    @Transactional
    public OrderDTO updateOrder(UUID orderId, OrderDTO orderDto) {
        // Find existing order
        Order existingOrder = orderRepository.findById(orderId)
                .orElseThrow(() -> new RuntimeException("Order not found with id: " + orderId));
        
        // Update order fields
        if (orderDto.getName() != null) {
            existingOrder.setName(orderDto.getName());
        }
        if (orderDto.getQty() > 0) {
            existingOrder.setQty(orderDto.getQty());
        }
        if (orderDto.getPrice() > 0) {
            existingOrder.setPrice(orderDto.getPrice());
        }
        
        // Save updated order
        Order updatedOrder = orderRepository.save(existingOrder);
        
        // Map to DTO and return
        OrderDTO updatedDto = orderMapper.mapOrderToDTO(updatedOrder);
        
        // Optionally publish update status to RabbitMQ
        OrderStatus orderStatus = new OrderStatus(updatedDto, "UPDATED", "Order updated successfully");
        template.convertAndSend(MessagingConfig.EDU_EXCHANGE, MessagingConfig.EDU_ROUTING_KEY, orderStatus);
        
        return updatedDto;
    }
}
